### ISSUE TITLE
token published in codebase

### ISSUE THREAD

**Issue by DefiantBidet** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#1]
saw reddit thread in `/r/javascript` about this repo and a user in there commented about a token being exposed.
adding this just to highlight it in the actual repo

there's a token exposed in the r.js file under the scraper

**Comment by ktynski** [comment]
Token has been changed and no longer works. It's still in the history, but no big deal since it is expired now and a new private token has been generated.
