### ISSUE TITLE
Question about felonies-13-19 cleaned CSV

### ISSUE THREAD

**Issue by faithlierheimer** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#117]
Hi @ktynski , I have a question about the felonies data, I downloaded it to play around and see if I could get any interesting insight out of it. What location is this from?

**Comment by OscarVanL** [comment]
Hi, this CSV is from Florida Palm Beach county's court records. The scraper used can be found at https://github.com/Police-Data-Accessibility-Project/Scrapers/tree/master/USA/FL/Palm_Beach/Court

**Comment by faithlierheimer** [comment]
Thank you @OscarVanL
