### ISSUE TITLE
Trouble joining the slack

### ISSUE THREAD

**Issue by jonathanleek** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#118]
I tried joining the slack, but it doesn't seem to be emailing me when it claims it is. Have attempted several times. Is link expired?

**Comment by charlex** [comment]
Hi @jonathanleek 

Does this link work for you? https://join.slack.com/t/policeaccessibility/shared_invite/zt-ego0gttu-MFCPQ6m9aIKiHhOqTRywMQ

**Comment by charlex** [comment]
Or try and use the link at https://www.reddit.com/r/DataPolice/ in the sidebar:

![Screen Shot 2020-06-16 at 3 32 17 AM](https://user-images.githubusercontent.com/1542740/84745102-16b82e80-af82-11ea-8b6e-24588ffaaca7.png)

**Comment by charlex** [comment]
Or send me an email and I'll invite you personally at hcbodkin [at] gmail [dot] com

**Comment by jonathanleek** [comment]
It finally kicked over, I'm in now. Slack must have been having some issues?

**Comment by NapsterInBlue** [comment]
Hey y'all. Can someone email me a fresh link at this username @ gmail?

Please and thanks!
