### ISSUE TITLE
The Slack Invite Link In README and CONTRIBUTING.md Not Working

### ISSUE THREAD

**Issue by RaymondFallon** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#125]
The links to join the Slack channel in the documentation appear to have expired. They both link to a Slack page with the following message:

> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by alphabet5** [comment]
This appears to have been resolved. Are you still experiencing this @RaymondFallon?

**Comment by RaymondFallon** [comment]
Nope, looks good now, thanks for the ping!
