### ISSUE TITLE
Create database of community skillsets

### ISSUE THREAD

**Issue by ktynski** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#17]
This can be compiled from the #_introduceyourself slack channel, just needs someone to do the tedious work of going through it all.

**Comment by shredinger137** [comment]
That work would continue well after the initial run through. What about a spreadsheet/catalog/whatever that people can add themselves too, or maybe submit a form for? That way the maintenance can be taken out of it.

**Comment by ktynski** [comment]
Currently being worked on by Mackenzie Custer and a few others in the slack.

**Comment by amsully** [comment]
Should this be closed? The only addition I would make is to add a 'Topic' to #_introduceyourself that links to the google sheet or google form created. 

Sheet
https://docs.google.com/spreadsheets/d/1wMnHGNkKVOkJ2ryNHbAza7WYKlF2eToFyNenH94efJ8/edit?ts=5ed42535#gid=0

Form: https://docs.google.com/forms/d/e/1FAIpQLSfk61RZ3iz9_BqK9NkO7ZSccw7yls4OhYrI5hUU_ATHfUpZ1g/viewform

**Comment by jlintag** [comment]
I'm going to close this because we do have the form; I won't recommend using the existing sheet though.
