### ISSUE TITLE
Update Slack link within CONTRIBUTING.md

### ISSUE THREAD

**Issue by restlessdesign** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#20]
Seems this link has expired.

**Comment by ktynski** [comment]
still working for me, can anyone else confirm it is broken?

**Comment by inventionlabsSydney** [comment]
Can confirm the link still works for me incognito 👍

**Comment by restlessdesign** [comment]
I think it is a parsing or rendering issue with Github markdown triggered by the curly brackets:

**Broken**
{https://join.slack.com/t/policeaccessibility/shared_invite/zt-eji7fh9w-slynNpPJtcGLUUhbhBmbTg}

If they aren’t necessary, removing them should work:
https://join.slack.com/t/policeaccessibility/shared_invite/zt-eji7fh9w-slynNpPJtcGLUUhbhBmbTg

If they are necessary, adding a space between the brackets and URL might serve as a workaround:
{ https://join.slack.com/t/policeaccessibility/shared_invite/zt-eji7fh9w-slynNpPJtcGLUUhbhBmbTg }

**Comment by EvanHahn** [comment]
Made #28, which solves the issue by making some prose clickable ("click here to..." instead of a full URL). Feel free to close or suggest changes.
