### ISSUE TITLE
Establish a project License

### ISSUE THREAD

**Issue by nicholastmosher** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#23]
Hey everyone, I've started to see people talk about opening PRs and actually merging code (e.g. scrapers) already, but I'm concerned about the fact that there's no code license in this repository yet. IANAL, but my loose understanding is that if the repository does not have an explicit license, then the authors of each contribution have full copyright over their work, and others (i.e. the project owner) would not be able to assign a license to the project without the explicit approval of all the existing contributors. So I suppose I'd like to open up this issue as a place to discuss licenses for the project.

I've heard talk that it might be desirable to license the software in one way and the collected data in another. `@KMK` on slack suggested GNU GPLv3 for the software license, which I think would be great for this project. For anyone who's not familiar, here's a good summary of it from https://choosealicense.com/licenses/gpl-3.0/

>  Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

**Comment by ConstantineK** [comment]
Made a PR that adds it if that's what is decided is needed #24

**Comment by ConstantineK** [comment]
@nicholastmosher sorry I didnt tag the commit properly, but this issue should be resolved if you want to close it.

**Comment by nicholastmosher** [comment]
Awesome, thanks for doing that!
