### ISSUE TITLE
Define CSV target schema for web scrapers

### ISSUE THREAD

**Issue by amsully** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#25]
# Goal

Provide a package for web scrapers to validate processed data. 

# List of Features

- Minimal CSV schema that is extensible (research if there are **Existing Formats**).
- Definitions of all schema items ('Plain English' terms of what it is with unique identifier.).
- Data Types. Validation criteria for specific data types (ie: ISO formatted dates / max length / min length).
- Tests to reduce regressions.
- Easy distribution method. Location to install package (NPM, PIP, etc)
- Graceful and useful error handling (ie "Record row 10302 contains invalid FIPS code")
     - Includes suggestions for moving forward to enable devs with action items (thanks @ nicholastmosher) 

# Decisions

- TODO: Place upcoming meeting info between #database_general and #scrapers_general here
- Location of this code (repo/package)
- Technology (I propose **python** as it is accessible for many people. Although I would like to do something like Scala, Go, or Java. Rust was also mentioned which I'm OK with)
- ...

Please add/comment on features scoped to **CSV FORMATTING ONLY** in this issue. 

# Out of scope to this discussion

- Storing RAW Version of webpages for future fidelity checks and snapshotting
- Data Lake/Data Warehouse/RDBMs discussion
- ...

I'll update this as we think through what is required for this. Refer to the README for the current list of minimum fields (and information about expected PII)

To project owners: Don't be afraid to step on my toes here and edit/update this issue however you want. 

## PS If you are reading this and looking to get caught up on info

The #database_general slack channel has a link to the first database meeting and the meeting minutes can be found here: https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/blob/master/Meeting%20Minutes/db_team_minutes/5_31_2020.md

**Comment by nicholastmosher** [comment]
Thanks for putting this together @amsully!

If I'm reading this correctly, here you're primarily proposing a utility for taking a schema and a dataset and validating that the dataset matches the schema, is that correct? I think that's a great idea to go with this project. Some responses to your points:

* I'd like to emphasize the importance of the *Graceful and useful error handling* point by saying that a friendly user interface can sometimes make or break the participation of some users. An automated tool like this can be made much more helpful if it can also offer *suggestions for moving forward* rather than just "errors". For example, if our schema has a column for "county name" and perhaps we have a particular set of name codes for counties in the U.S., then if a dataset is using the wrong format for counties (say, there are hyphens when there shouldn't be, or a fully spelled-out name when it should be a county code, etc.). If the validator is able to say "hey, you've got the wrong county format, check out our county code set", it's give people actionable information.

* For the location of the code, I'm advocating that this project should probably start out by using a monorepo (I just found a good summary of some of the advantages [here](https://danluu.com/monorepo/), where different components are simply placed into different directories. I'd like to see all of the code for the project start in this repo. Perhaps we could have a `scrapers/` top-level directory, with the validator in `scrapers/validator`.

* For technology, this utility seems really well-suited for a command-line tool. My personal choice for something like this would be Rust (it's _fast_, has great csv support, easy to distribute), but I understand that this project would want to make a decision based on the experience of the participants, so I'm also just fine with using Python or any other language.

* This should probably be configurable, either with command-line options or a configuration file or environment variables. Options might include whether to include or exclude PII like you mentioned, how strict to be, etc.

**Comment by amsully** [comment]
> Thanks for putting this together @amsully!
> 
> If I'm reading this correctly, here you're primarily proposing a utility for taking a schema and a dataset and validating that the dataset matches the schema.

My intention was that a web scraper implementation would have an output (CSV). That output would be validated with a `pdap-validator` to ensure it meets minimum sanitation requirements. If by 'dataset' you mean config files that have metadata around fields (and perhaps allowable codes) then yes.

> 
> * I'd like to emphasize the importance of the _Graceful and useful error handling_ point by saying that a friendly user interface can sometimes make or break the participation of some users...

Totally agreed. Our end-user will be other contributors to this project. There is a TON of work to do for the web scrapers so it's important to make this step easy.

> * For the location of the code, I'm advocating that this project should probably start out by using a monorepo (I just found a good summary of some of the advantages ...

I'm on the fence here and am not really in any camp. If I wanted to get started on this project I think it would be daunting to see a repo that contains User-Interface code, 150 web scraper implementations, backend-code, infrastructure code, an Android App and some ReactNative app all grouped together. vs going to github.com/Police-Data-Accessibility-Project/pdap-webscrapers and knowing it will only be about web scrapers (and all issues/pull requests are related to web scraping). I posted my opinion on slack: 

```I'm ok with either: 
1. Start with 1 repo with the expectation to break it out sooner rather than later. 
2. 1 repo with rigid specification defined as soon as possible.
The issue tracker will be very noisy for contributors who want to only work on web scraper issues or ui issues. You can tag/sort/filter issues, but that requires a lot of manual work for the core team

```

> * For technology, this utility seems really well-suited for a command-line tool...

Totally agree. Something a web scraper developer could add to there code via a package import and a data scientist could run with a simple CLI command. I would be fine with Rust as well as long as the distribution is simple for the end-user. I do think python/javascript has eaten the world with these types of applications (web scrapers) so at a minimum, we would need interfaces to those languages.

> * This should probably be configurable, either with command-line options or a configuration file or environment variables

Absolutely

**Comment by amsully** [comment]
Also about coding language...the first step (defining the schema) is actually code-agnostic so let's not dive too deep into implementation details yet.

**Comment by nicholastmosher** [comment]
> I'm on the fence here and am not really in any camp. If I wanted to get started on this project I think it would be daunting to see a repo that contains User-Interface code, 150 web scraper implementations, backend-code, infrastructure code, an Android App and some ReactNative app all grouped together. vs going to github.com/Police-Data-Accessibility-Project/pdap-webscrapers and knowing it will only be about web scrapers (and all issues/pull requests are related to web scraping).

I think that this aspect of a large project being "daunting" might be an orthogonal issue to how the project is structured. We can tackle contributor onboarding by having a friendly README and a description of where the various components lie. We should also have a quick "getting started" guide for each component. To throw my own opinion in there, sometimes I can find that a project which is spread among many repos can be more difficult to navigate because it's not always obvious how the repos are related.

**Comment by nicholastmosher** [comment]
It occurred to me that this seems like too common a use-case to be an original endeavor. I went for a quick search and found this [CSV Validator](http://digital-preservation.github.io/csv-validator/) and corresponding [CSV Schema Language](http://digital-preservation.github.io/csv-schema/). I haven't dug too deep into them yet but I'm going to keep reading. It might suit some or all of our needs here.

**Comment by harootune** [comment]
Following up on @nicholastmosher 's post:

We can anticipate that a decent number of our scrapers will be using Python to do their work (though certainly not all of them). The CSV Validator that was mentioned above offers Java and Scala APIs. As we consider how to construct our schema, it seems reasonable to me that we should choose a schema format which is well-supported across the ecosystems we anticipate our coders working in (Python, Java, potentially Node etc).

CSV Schema seems suitable for most of our purposes. However, there does not appear to be any well-documented Python package for parsing the CSV Schema as defined in the [unofficial specification document](http://digital-preservation.github.io/csv-schema/csv-schema-1.1.html). I thought [PyCSVSchema](https://github.com/crowdskout/PyCSVSchema) may have been such a package, but instead it seems like its an implementation of [this JSON vocabulary](https://github.com/csv-schema/csv-schema), which is also named "CSV Schema" but does not appear to be working from/adapting the same specification.

Considering the ubiquity of JSON, shooting for a JSON-based schema format seems like a good idea to me, if we wish to take advantage of pre-existing csv validation packages in the various ecosystems the scrapers will be working within. I'm not sure exactly which existing format is best for our purposes, but I'd guess its likely an adaptaton of [json-schema](https://json-schema.org/), which many Python-based csv validation packages seem to use as the basis for their schema files.

One general thing I'm not sure about is what is meant by the word "extensible" in our first feature. Do we have a clear idea of what we mean by that? Do we want scrapers to be able to define custom fields as needed? If so, how do we make unexpected columns play nicely with whatever validators we choose to use, and enforce data sanitization for them?

I'm a bit of a novice still, so if anything I've said here is off-base, sincerest apologies.

**Comment by amsully** [comment]
> it seems reasonable to me that we should choose a schema format which is well-supported across the ecosystems we anticipate our coders working in (Python, Java, potentially Node etc).

I agree. We should aim to have a generic schema and implement a validator for each language used.

> However, there does not appear to be any well-documented Python package for parsing 

Yes my initial (very minimal) research didn't uncover an obvious choice so we will need to assess the options.

> Considering the ubiquity of JSON, shooting for a JSON-based schema format seems like a good idea to me...but I'd guess its likely an adaptaton of [json-schema](https://json-schema.org/), 

Yep I agree that a JSON-based schema is a lead candidate

> One general thing I'm not sure about is what is meant by the word "extensible"

Extensible implies everything is dynamic. So column order should not matter, the addition of new data should be clear and the addition of new data types should be allowed. Allowing scrapers to define custom fields is **not** the goal (but we could have the validator ignore unknown columns)


I will start experimenting tonight with some of the proposed options

**Comment by justjoeactually** [comment]
I've been using json-schema with golang and javascript a good bit lately, it works well and I'd expect it work fine for us. And it doesn't have to be an either-or situation, I can imagine where we can validate and ingest both csv and json.

**Comment by amsully** [comment]
> I can imagine where we can validate and ingest both csv and json.

The intent is to write the schema in JSON (if we can't find a universal schema validator to our liking), not validate scraped JSON data. JSON is a lead candidate in terms of a protocol to define our schema (alternatives are YAML, XML, etc)

**Comment by amsully** [comment]
Update from me: I've assessed a few of the options and they are all lackluster.

Here is a small writeup about why: 

Unfortunately, there is no standard uniformly accepted by the web. This makes it difficult to handle large dynamic CSV files. W3 made a recommendation group for a CSV implementation that appears stale: https://www.w3.org/TR/tabular-metadata/

The specification implementation has no meaningful code updates in 4 years https://github.com/w3c/csvw and there are no forks that appeared to carry on the torch.


With that said my proposal is to utilize JSON-Schema to define a 'Log Event'. The validator (written in however many languages) will go through a CSV row by row, turn the row into a json object (<ColumnHeader>:<Value>) and validate on the json-schema.

I don't see many downsides to this. JSON-Schema is heavily adopted, implementation will be straight forward for any language.

**Comment by nicholastmosher** [comment]
@amsully I wrote a little utility to help with this, https://github.com/nicholastmosher/jsv

I was originally going to make it a PR to this repo but it seemed like a standalone thing that could be useful in other contexts as well. It's not super fully-featured yet but it should be pretty good for some basic validation.
