### ISSUE TITLE
Set up CI for scrapers

### ISSUE THREAD

**Issue by mcsaucy** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#57]
Maybe Travis?

**Comment by CsabaAlmasi** [comment]
I highly recommend GitHub actions since it's easy to integrate with

**Comment by mcsaucy** [comment]
Seems reasonable. I've got zero experience in this space, if anyone wants to lead that charge.

The only thing I can see being somewhat challenging is how "freeform" our project layout is presently. We've got Python and Node code presently (with more stuff likely on the way), so we'll likely need some way to accommodate those differences.

I'm throwing together some makefiles presently so we can at least rely upon `make test`.

**Comment by mcsaucy** [comment]
This is done in https://github.com/Police-Data-Accessibility-Project/Scrapers. We've got a pretty simple pytest approach for now and can expand as needed.
