### ISSUE TITLE
Slack Invite Link expired

### ISSUE THREAD

**Issue by adamlaz** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#75]
current link[1] in [CONTRIBUTING.md](https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/blob/master/CONTRIBUTING.md) is expired - can someone provide a new one? Thanks!

> 1. `https://join.slack.com/t/policeaccessibility/shared_invite/zt-eji7fh9w-slynNpPJtcGLUUhbhBmbTg`

![slacklinkbroken](https://user-images.githubusercontent.com/2012381/83824047-73bf0500-a6a3-11ea-9d6c-5dccd07be0aa.gif)

**Comment by dongately** [comment]
can this be closed
