### ISSUE TITLE
Update Wiki with Project Description

### ISSUE THREAD

**Issue by nicholastmosher** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#83]
I've transcribed the following document that was posted in Slack and added it to the wiki home page

![image](https://user-images.githubusercontent.com/4210949/83896698-8fb5bb80-a722-11ea-9bbb-7cf90e22491b.png)

You can preview the wiki page on [my fork](https://github.com/nicholastmosher/Police-Data-Accessibility-Project/wiki). Once you're ready to merge, you can use [this URL for the forked wiki repo](https://github.com/nicholastmosher/Police-Data-Accessibility-Project.wiki.git)

**Comment by nicholastmosher** [comment]
Ah, I should make a note here that this is not quite a direct transcription. In the wiki entry, I replaced all instances of "Product" with "Project" because to me, "Product" invokes the connotation that this will be utilized for profit, a sentiment which I want to squash before it ever appears. If anybody disagrees with me we can discuss that here

**Comment by jlintag** [comment]
I think "Product" => "Project" is ok for now. Do open a ticket to discuss it specifically though as it may be something that we need to intentionally revisit.

**Comment by jlintag** [comment]
Awesome work though, thank you.
