### ISSUE TITLE
Add "Organization" page to the Wiki

### ISSUE THREAD

**Issue by nicholastmosher** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#84]
I've added an adaptation of this post from the `#_announcements` channel in the team slack to the Wiki as the "Organization" page: https://policeaccessibility.slack.com/archives/C014C0S31A9/p1590889096146300

These changes can be viewed [on my fork of the wiki](https://github.com/nicholastmosher/Police-Data-Accessibility-Project/wiki/Organization).

I have made some changes that I'd like to point out for the sake of transparency:

* I replaced all instances of "Product team" with "Engineering team" per the discussion here: https://policeaccessibility.slack.com/archives/C014X1CQ63B/p1591373296396400

* When referring to the "Product" itself, I changed the text to instead refer to "the PDAP system". Instead of saying the project has a "product focus", I said it has a "software-deliverable focus".

* I shortened the name of the "Security & Operations" team to "Operations", since the original writeup itself did shorten that name in the description.

* Instead of saying that "the conversation around the mission statement is being discussed offline", I said "the conversation around the mission statement is being discussed among the leadership". This was done with the purpose of expressing more transparency.

**Comment by nicholastmosher** [comment]
I just added to this branch the descriptions of the engineering subteams from this draft: https://policeaccessibility.slack.com/archives/C014C0S31A9/p1590960541162800

**Comment by nicholastmosher** [comment]
I just added the descriptions of the recognition subteams from this draft: https://policeaccessibility.slack.com/archives/C014C0S31A9/p1591032843177600

**Comment by jlintag** [comment]
These are all excellent changes, thank you.
