### ISSUE TITLE
Adjust Engineering team definition on Organization page in the wiki to match latest

### ISSUE THREAD

**Issue by jlintag** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#85]
https://policeaccessibility.slack.com/archives/C014C0S31A9/p1591308050464300

**Comment by nicholastmosher** [comment]
Ah you know what, I think I saw this document was out there but I didn't connect the dots that this was an update of the previous post. I've pushed an update to my fork of the wiki.

**Comment by jlintag** [comment]
Updated wiki
