### ISSUE TITLE
Add Operations team definition on Organization page in the wiki to match latest

### ISSUE THREAD

**Issue by jlintag** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#86]
https://policeaccessibility.slack.com/archives/C014C0S31A9/p1590971223167000

**Comment by nicholastmosher** [comment]
@jlintag this is updated in [my local fork of the wiki](https://github.com/nicholastmosher/Police-Data-Accessibility-Project/wiki/Organization)
