### ISSUE TITLE
Sometimes Case Numbers in Bay County represent two separate cases

### ISSUE THREAD

**Issue by OscarVanL** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#94]
After scraping continually for a day, my scraper for Bay County stopped working properly.

This was because some case numbers on the portal result are associated with more than one case...

To reproduce:

Go to the [portal's search page](https://court.baycoclerk.com/BenchmarkWeb2/Home.aspx/Search) and search for case `19002535` and a single result will appear. Now search for case `19002536` and a search window with two cases will appear: `19002536CFMB` and `19002536CFMA`, a behaviour that was not seen before.

This should not be hard to resolve, each case number on this 'Case Search Results' window should be opened and scraped. 

Currently, the `search_portal()` function treats arriving at the `Case Search Results` window as a failed search, as the same window opens when there are 0 search results. This assumption must also be changed.

If you intend to reproduce the behaviour, take a cell in the `bay-county-scraped.csv` output and change the bottom row's `CaseNum` to `19002535` and it will start scraping from the broken record.

I have created an issue as I do not intend to immediately resolve this. Others are free to have a go, I know @mcsaucy has been contributing to this scraper a lot. :) If no one takes it up, I will get around to it.

**Comment by lzoz** [comment]
Made a pull request for this #98

**Comment by mcsaucy** [comment]
Did #98 completely fix this?

**Comment by OscarVanL** [comment]
> Did #98 completely fix this?

Yes, I tried the fix and it works as expected. I'll close this. Thanks again @lzoz :)
