### ISSUE TITLE
Standardize structure for scraper dirs

### ISSUE THREAD

**Issue by mcsaucy** [Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#97]
'Counties/Florida' is wonky, but we'll definitely hit county name collisions otherwise. Maybe we should have `Municipalities/Florida/Bay` or something? We should also probably ween ourselves off of spaces (and dashes) as path components, as many languages don't like that.

This could end up looking like:
```
Municipalities/Florida/Bay/...
Municipalities/Florida/St_Johns/...
Municipalities/New_York/New_York_City/...
```

**Comment by nfrostdev** [comment]
We'll be discussing mono vs multi repository structure this Sunday. I hope we can have an answer for you soon!

**Comment by Hakeley** [comment]
I'm thinking that we use a structure like 
```
Scrapers/Florida/Counties/Palm_Beach/court_records
Scrapers/Florida/Counties/Palm_Beach/police_complaints
Scrapers/Florida/Counties/Palm_Beach/incident_reports
...
```
for a few reasons.
1) It's intuitive, descending in geographic size.
2) There are 20,000 municipalities in the US but only around 3,000 counties, so it would be a lot easier to navigate.
3) Municipalities are more likely to have their name changed, to be created, or to become obsolete than counties are. And I don't like the idea of constantly changing these folder names.
4) We have multiple types of content from each geographic location to scrape which (I think) are usually coming from different websites, and it would make sense to have a scraper per website. Hence the division between court records, police complaints, and incident reports, each for their respective scraper. We can enumerate these records once the MVP is established.

And for a portal that contains information for multiple counties, we could put the scraper for that portal in one county's folder and then create a symbolic link to it in other counties folders. I'm not sure if that would be confusing though; but it's my best solution to how unstandardized these sites are with respect to the geographies they cover.

Just some thoughts, but I'm curious to see what they come up with in the Sunday meeting.

**Comment by nfrostdev** [comment]
Pulling the trigger on this, please proceed with `$STATE/$COUNTY/$RECORD_TYPE` under https://github.com/Police-Data-Accessibility-Project/Scrapers.

I don't care what casing convention is used as long as it is consistent.
If we run into issues for "State" police that don't have an association with county we should probably just decide on a folder to throw them in under "State". We can dig into that with the new repository.

Thank you for all of your hard work on this project @mcsaucy, and for the suggestion @Hakeley!
